# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: sylvie.dagoret-campagne@ijclab.in2p3.fr
author_name: Sylvie Dagoret-Campagne
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: mysitcomrail
project_license: MIT
project_name: mysitcomrail
project_organization: LSSTDESC
python_versions:
- '3.9'
- '3.10'
- '3.11'
